project_id = "kvzzfthrefdisuohzfws"

[functions.chronicle]
verify_jwt = false

[functions.citystates]
verify_jwt = false

[functions.wonder]
verify_jwt = false

[functions.cityprofile]
verify_jwt = false

[functions.diplomacy-reply]
verify_jwt = false

[functions.extract-traits]
verify_jwt = false
