/**
 * City district catalogue — two families that depend on each other.
 *
 * Residential districts house people: they raise housing capacity and, because those
 * households consume, they raise basket demand. They also provide the labour pool.
 * Production districts turn that labour into goods for one chosen demand basket.
 *
 * One residential district staffs PRODUCTION_PER_RESIDENTIAL production districts.
 * Unstaffed production districts stand idle and supply nothing.
 */

export const PRODUCTION_PER_RESIDENTIAL = 2;

export interface DistrictBlueprint {
  key: string;
  name: string;
  district_type: "residential" | "production";
  population_capacity?: number;
  /** Extra basket demand generated by the households (spread over the tiers). */
  demand_bonus?: number;
  /** Production districts: units delivered into the chosen basket each turn. */
  basket_output?: number;
  basket_quality?: number;
  build_cost_wealth: number;
  build_cost_wood?: number;
  build_cost_stone?: number;
  build_turns: number;
  grain_modifier?: number;
  wealth_modifier?: number;
  production_modifier?: number;
  stability_modifier?: number;
  peasant_attraction?: number;
  burgher_attraction?: number;
  /** Baskets this district may be set to produce; empty means all baskets. */
  baskets?: string[];
  description: string;
}

/**
 * Housing — population, demand and the labour that staffs production districts.
 * CALIBRATION: one residential quarter must carry two level-1 production centres
 * (2 × 100 jobs at the default active share of inhabitants).
 */
export const RESIDENTIAL_DISTRICTS: DistrictBlueprint[] = [
  { key: "quarter", name: "Obytná čtvrť", district_type: "residential", population_capacity: 400, demand_bonus: 2.5,
    build_cost_wealth: 25, build_cost_wood: 25, build_cost_stone: 10, build_turns: 2, stability_modifier: 1, peasant_attraction: 6,
    description: "Hustá zástavba domů pro rodiny řemeslníků a rolníků." },
  { key: "tenements", name: "Nájemní domy", district_type: "residential", population_capacity: 640, demand_bonus: 4,
    build_cost_wealth: 45, build_cost_wood: 30, build_cost_stone: 25, build_turns: 3, stability_modifier: -1, burgher_attraction: 8,
    description: "Vysoké nájemní domy — mnoho lidí, méně klidu." },
  { key: "colony", name: "Dělnická kolonie", district_type: "residential", population_capacity: 480, demand_bonus: 2.8,
    build_cost_wealth: 30, build_cost_wood: 35, build_cost_stone: 5, build_turns: 2, production_modifier: 3, peasant_attraction: 10,
    description: "Kolonie u dílen a polí, láká pracovní sílu." },
  { key: "suburb", name: "Předměstí", district_type: "residential", population_capacity: 320, demand_bonus: 1.8,
    build_cost_wealth: 20, build_cost_wood: 20, build_cost_stone: 5, build_turns: 1, stability_modifier: 2, peasant_attraction: 4,
    description: "Rozvolněné domky na okraji města." },
];

/** Workshops — each one is set to a single demand basket and supplies it every turn. */
export const PRODUCTION_DISTRICTS: DistrictBlueprint[] = [
  { key: "farm_belt", name: "Hospodářský pás", district_type: "production", basket_output: 6, basket_quality: 1,
    build_cost_wealth: 30, build_cost_wood: 20, build_cost_stone: 5, build_turns: 2, grain_modifier: 4,
    baskets: ["staple_food", "fuel", "drinking_water", "feast"],
    description: "Pole, sady a pastviny na okraji města." },
  { key: "craft_row", name: "Řemeslnická čtvrť", district_type: "production", basket_output: 5, basket_quality: 2,
    build_cost_wealth: 40, build_cost_wood: 30, build_cost_stone: 15, build_turns: 2, production_modifier: 4,
    baskets: ["tools", "basic_clothing", "metalwork", "construction", "luxury_clothing"],
    description: "Dílny tkalců, kovářů a truhlářů v jedné ulici." },
  { key: "manufactory_yard", name: "Manufakturní dvůr", district_type: "production", basket_output: 8, basket_quality: 2,
    build_cost_wealth: 70, build_cost_wood: 40, build_cost_stone: 35, build_turns: 3, production_modifier: 6, stability_modifier: -1,
    description: "Velký výrobní dvůr s dělenou prací — vyšší výkon, více špíny." },
  { key: "depot_quarter", name: "Skladová čtvrť", district_type: "production", basket_output: 6, basket_quality: 1,
    build_cost_wealth: 35, build_cost_wood: 25, build_cost_stone: 20, build_turns: 2, wealth_modifier: 3,
    baskets: ["storage_logistics", "construction", "admin_supplies", "fuel"],
    description: "Sklady, váhy a povozy — zásobování a rozvoz." },
  { key: "arsenal_quarter", name: "Zbrojní čtvrť", district_type: "production", basket_output: 5, basket_quality: 2,
    build_cost_wealth: 60, build_cost_wood: 30, build_cost_stone: 40, build_turns: 3,
    baskets: ["military_supply", "metalwork", "tools"],
    description: "Kovárny a sklady výzbroje pod dohledem posádky." },
];

export const ALL_DISTRICTS = [...RESIDENTIAL_DISTRICTS, ...PRODUCTION_DISTRICTS];

export function districtBlueprint(key: string): DistrictBlueprint | undefined {
  return ALL_DISTRICTS.find(d => d.key === key);
}

/** How many production districts the given number of residential districts can staff. */
export function staffingCapacity(residentialCount: number): number {
  return residentialCount * PRODUCTION_PER_RESIDENTIAL;
}
