ALTER TABLE public.city_districts
  ADD COLUMN IF NOT EXISTS basket_key text,
  ADD COLUMN IF NOT EXISTS basket_output numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS basket_quality integer NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS demand_bonus numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS is_staffed boolean NOT NULL DEFAULT true;

CREATE INDEX IF NOT EXISTS city_districts_city_type_idx ON public.city_districts (session_id, city_id, district_type);

COMMENT ON COLUMN public.city_districts.basket_key IS 'Production districts: which of the 12 canonical demand baskets this district supplies.';
COMMENT ON COLUMN public.city_districts.is_staffed IS 'False when no residential district supports this production district (2 production per residential).';
COMMENT ON COLUMN public.city_districts.demand_bonus IS 'Residential districts: extra basket demand generated by the households living here.';