
-- Add hybrid node classification and scoring columns
ALTER TABLE public.province_nodes
  ADD COLUMN IF NOT EXISTS node_class text NOT NULL DEFAULT 'generic',
  ADD COLUMN IF NOT EXISTS node_score numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS faith_output numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS faith_pressure numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS collapse_severity numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS food_value numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS sacred_influence numeric NOT NULL DEFAULT 0;

-- node_class values:
-- Geographic (fixed from map): transit, resource, fortress
-- Functional (emergent from flow data): trade_hub, food_basin, sacred, generic

COMMENT ON COLUMN public.province_nodes.node_class IS 'Hybrid classification: geographic types (transit/resource/fortress) fixed from terrain, functional types (trade_hub/food_basin/sacred) emergent from flow data';
COMMENT ON COLUMN public.province_nodes.node_score IS 'Composite opportunity score for AI settlement placement decisions';
COMMENT ON COLUMN public.province_nodes.faith_output IS 'Faith flow generated by this node (from clerics + temples)';
COMMENT ON COLUMN public.province_nodes.faith_pressure IS 'Accumulated faith pressure from connected sacred nodes';
COMMENT ON COLUMN public.province_nodes.collapse_severity IS 'Tiered collapse impact if this node is lost (0-100 based on importance)';
COMMENT ON COLUMN public.province_nodes.food_value IS 'Food production potential of this node (grain flow)';
COMMENT ON COLUMN public.province_nodes.sacred_influence IS 'Religious significance score affecting faith pressure radius';
