-- Parent-scoped legacy and projection tables.
DROP POLICY IF EXISTS "Public access to legacy military map" ON public.legacy_military_map;
DROP POLICY IF EXISTS public_read_legacy_military_map ON public.legacy_military_map;
CREATE POLICY legacy_military_map_session_access
ON public.legacy_military_map FOR ALL TO authenticated
USING (EXISTS (
  SELECT 1 FROM public.military_stacks s
  WHERE s.id = legacy_military_map.stack_id
    AND app_private.is_session_member(s.session_id)
))
WITH CHECK (EXISTS (
  SELECT 1 FROM public.military_stacks s
  WHERE s.id = legacy_military_map.stack_id
    AND app_private.is_session_member(s.session_id)
));

DROP POLICY IF EXISTS node_inventory_all ON public.node_inventory;
DROP POLICY IF EXISTS node_inventory_select ON public.node_inventory;
CREATE POLICY node_inventory_session_access
ON public.node_inventory FOR ALL TO authenticated
USING (EXISTS (
  SELECT 1 FROM public.province_nodes n
  WHERE n.id = node_inventory.node_id
    AND app_private.is_session_member(n.session_id)
))
WITH CHECK (EXISTS (
  SELECT 1 FROM public.province_nodes n
  WHERE n.id = node_inventory.node_id
    AND app_private.is_session_member(n.session_id)
));

DROP POLICY IF EXISTS "Public access to settlement resource profiles" ON public.settlement_resource_profiles;
DROP POLICY IF EXISTS public_read_settlement_resource_profiles ON public.settlement_resource_profiles;
CREATE POLICY settlement_resource_profiles_session_access
ON public.settlement_resource_profiles FOR ALL TO authenticated
USING (EXISTS (
  SELECT 1 FROM public.cities c
  WHERE c.id = settlement_resource_profiles.city_id
    AND app_private.is_session_member(c.session_id)
))
WITH CHECK (EXISTS (
  SELECT 1 FROM public.cities c
  WHERE c.id = settlement_resource_profiles.city_id
    AND app_private.is_session_member(c.session_id)
));

DROP POLICY IF EXISTS "Public access to wonder draft images" ON public.wonder_draft_images;
DROP POLICY IF EXISTS public_read_wonder_draft_images ON public.wonder_draft_images;
CREATE POLICY wonder_draft_images_session_access
ON public.wonder_draft_images FOR ALL TO authenticated
USING (EXISTS (
  SELECT 1 FROM public.wonders w
  WHERE w.id = wonder_draft_images.wonder_id
    AND app_private.is_session_member(w.session_id)
))
WITH CHECK (EXISTS (
  SELECT 1 FROM public.wonders w
  WHERE w.id = wonder_draft_images.wonder_id
    AND app_private.is_session_member(w.session_id)
));

-- Global reference catalogs are readable by players and writable only by admins/server code.
DO $$
DECLARE table_name text; p record;
BEGIN
  FOREACH table_name IN ARRAY ARRAY['goods','good_variants','resource_types','production_recipes']
  LOOP
    FOR p IN
      SELECT policyname FROM pg_policies
      WHERE schemaname='public' AND tablename=table_name AND cmd IN ('INSERT','UPDATE','DELETE','ALL')
    LOOP
      EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', p.policyname, table_name);
    END LOOP;
    EXECUTE format(
      'CREATE POLICY %I ON public.%I FOR ALL TO authenticated USING (public.has_role(auth.uid(), ''admin'')) WITH CHECK (public.has_role(auth.uid(), ''admin''))',
      left(table_name || '_admin_write', 63), table_name
    );
  END LOOP;
END
$$;

-- Media is generated by trusted server functions; clients only need public reads.
DROP POLICY IF EXISTS "Authenticated users can upload wonder images" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated users can upload building images" ON storage.objects;
DROP POLICY IF EXISTS "Users can update their own wonder images" ON storage.objects;
DROP POLICY IF EXISTS "Users can delete their own wonder images" ON storage.objects;
DROP POLICY IF EXISTS "Users can update their own building images" ON storage.objects;
DROP POLICY IF EXISTS "Users can delete their own building images" ON storage.objects;